FROM microsoft/aspnetcore-build:2 as builder

WORKDIR /src/common/Domain
COPY /src/common/Domain/Domain.csproj .
RUN dotnet restore

WORKDIR /src/services/customer/Customer.Core
COPY /src/services/customer/Customer.Core/Customer.Core.csproj .
RUN dotnet restore

WORKDIR /src/services/customer/Customer.Logging
COPY /src/services/customer/Customer.Logging/Customer.Logging.csproj .
RUN dotnet restore

WORKDIR /src/services/customer/Customer.Data
COPY /src/services/customer/Customer.Data/Customer.Data.csproj .
RUN dotnet restore

WORKDIR /src/services/customer/Customer.EventPublisher
COPY /src/services/customer/Customer.EventPublisher/Customer.EventPublisher.csproj .
RUN dotnet restore

COPY /src/common/Domain/ /src/common/Domain/
COPY /src/services/customer/Customer.Core/ /src/services/customer/Customer.Core/
COPY /src/services/customer/Customer.Logging/ /src/services/customer/Customer.Logging/
COPY /src/services/customer/Customer.Data/ /src/services/customer/Customer.Data/
COPY /src/services/customer/Customer.EventPublisher/ /src/services/customer/Customer.EventPublisher/

WORKDIR /src/services/customer/Customer.EventPublisher
RUN dotnet publish -c Release -o /build 

FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY --from=builder /build .

ENTRYPOINT [ "dotnet", "Customer.EventPublisher.dll" ]