version: '3.3'
services:
  account-service:
    build:
      context: ./
      dockerfile: ./docker/AccountService/dockerfile
  customer-service:
    build:
      context: ./
      dockerfile: ./docker/CustomerService/dockerfile
  microservice-example-proxy:
    build:
      context: ./
      dockerfile: ./docker/Nginx/dockerfile
  account-client:
    build:
      context: ./
      dockerfile: ./docker/AccountClient/dockerfile
  account-view-service:
    build:
      context: ./
      dockerfile: ./docker/AccountView/dockerfile
      