version: '3.3'
services:
  #######################################
  # customer services
  #######################################
  customer-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7888:80"
    links:
      - elk
    depends_on:
     - microservice-example-mongo
     - elk

  #######################################
  # account services
  #######################################
  account-view-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7845:80"
    links:
    - elk
    depends_on:
      - microservice-example-sql
      - elk

  account-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7887:80"
    links:
      - elk
    depends_on:
      - microservice-example-mongo
      - elk
  
  account-listener:
    environment:
      - MONGODB=mongodb://microservice-example-mongo:27017
      - MESSAGE_QUEUE_URL=nats://microservice-example-queue:4222
      - ELK=http://microexample-elk:9200
      - CUSTOMER_URL=http://customer-service/
    links:
      - elk
    depends_on:
      - microservice-example-sql
      - microservice-example-queue
      - elk

  account-view-listener:
    environment:
      - SQL_CONNECTION=Server=microservice-example-sql;Initial Catalog=AccountView;User Id=sa;Password=PWord1!!!;
      - MESSAGE_QUEUE_URL=nats://microservice-example-queue:4222
      - ELK=http://microexample-elk:9200
    links:
      - elk
    depends_on:
      - microservice-example-sql
      - microservice-example-queue
      - elk
      
  #######################################
  # identity services
  #######################################
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5566:80"
    links:
      - elk
    depends_on:
      - microservice-example-sql
      - elk
  #######################################
  # infrastructure services
  #######################################   
  microservice-example-proxy:
    ports:
     # - "9885:80"
      - "9887:443"
    depends_on:
      - customer-service
      - account-service
      - account-view-service

  microservice-example-sql:
    ports:
      - "1515:1433"
    environment:
      SA_PASSWORD: "PWord1!!!"
      ACCEPT_EULA: "Y"

  microservice-example-mongo:
    ports:
      - "27017:27017"
      
  microservice-example-queue: 
    ports:
      - "9009:4222"
      - "9010:8222"

  elk:
    image: sebp/elk
    container_name: microexample-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  mongo-event-publisher:
    environment:
      - MONGODB=mongodb://microservice-example-mongo:27017
      - MESSAGE_QUEUE_URL=nats://microservice-example-queue:4222
      - ELK=http://microexample-elk:9200
    links:
      - elk
    depends_on:
      - microservice-example-mongo
      - microservice-example-queue
      - elk