version: '3.3'
services:
  microservice-example-mongo:
    image: mongo
    container_name: microservice-example-mongo

  microservice-example-sql:
    image: microsoft/mssql-server-linux
    container_name: microservice-example-sql

  account-service:
    image: microexample/accountservice:v1
    container_name: account-service

  customer-service:
    image: microexample/customerservice:v1
    container_name: customer-service

  account-view-service:
    image: microexample/account-view-service:v1
    container_name: account-view-service

  microservice-example-queue: 
    image: nats:linux
    container_name: microservice-example-mq

  account-client:
    image: microexample/account-client:v1
    container_name: account-client
    
  microservice-example-proxy:
    image: microexample/reverseproxy
    container_name: microservice-example-proxy
    