version: '3.3'
services:
  microservice-example-proxy:
    ports:
      - "9885:80"
      - "9887:433"
    depends_on:
      - customer-service
      - account-service
      - account-view-service

  microservice-example-sql:
    ports:
      - "1515:1433"
    environment:
      SA_PASSWORD: "PWord1!!!"
      ACCEPT_EULA: "Y"

  microservice-example-mongo:
    ports:
      - "27017:27017"

  account-view-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7845:80"
    links:
    - elk
    depends_on:
      - microservice-example-sql

  account-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7887:80"
    links:
      - elk
    depends_on:
      - microservice-example-mongo
      
  microservice-example-queue: 
    ports:
      - "9009:4222"

  customer-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7888:80"
    links:
      - elk
    depends_on:
     - microservice-example-mongo

  customer-event-publisher:
    environment:
      - MONGODB=mongodb://microservice-example-mongo:27017
      - MESSAGE_QUEUE_URL=nats://microservice-example-queue:4222
      - ELK=http://microexample-elk:9200
    links:
      - elk
    depends_on:
      - microservice-example-mongo
      - microservice-example-queue
  elk:
    image: sebp/elk
    container_name: microexample-elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"