version: '3.3'
services:
  account-service:
    build:
      context: ./
      dockerfile: ./docker/AccountService/dockerfile
  customer-service:
    build:
      context: ./
      dockerfile: ./docker/CustomerService/dockerfile
      