version: '3.3'
services:
 
  #######################################
  # customer services
  #######################################
  customer-service:
    image: microexample/customer-service:v1
    container_name: customer-service

  #######################################
  # account services
  #######################################
  account-service:
    image: microexample/account-service:v1
    container_name: account-service

  account-view-service:
    image: microexample/account-view-service:v1
    container_name: account-view-service

  account-listener:
    image: microexample/account-listener:v1
    container_name: account-listener

  account-view-listener:
    image: microexample/account-view-listener:v1
    #container_name: account-view-listener removing container name to allow docker to use --scale

  #######################################
  # client services
  #######################################
  account-client:
    image: microexample/account-client:v1
    container_name: account-client

  #######################################
  # infrastructure services
  #######################################
  microservice-example-queue: 
    image: nats:linux
    container_name: microservice-example-mq

  microservice-example-mongo:
    image: mongo
    container_name: microservice-example-mongo

  microservice-example-sql:
    image: microsoft/mssql-server-linux
    container_name: microservice-example-sql
    
  microservice-example-proxy:
    image: microexample/reverseproxy
    container_name: microservice-example-proxy

  mongo-event-publisher:
    image: microexample/mongo-event-publisher:v1
    container_name: mongo-event-publisher
  
    