version: '3.3'
services:
  #######################################
  # customer services
  #######################################
  customer-service:
    build:
      context: ./
      dockerfile: ./docker/CustomerService/dockerfile
  customer-event-publisher:
    build:
      context: ./
      dockerfile: ./docker/CustomerEventPublisher/dockerfile

  #######################################
  # account services
  #######################################
  account-service:
    build:
      context: ./
      dockerfile: ./docker/AccountService/dockerfile

  account-view-service:
    build:
      context: ./
      dockerfile: ./docker/AccountView/dockerfile
  
  account-view-listener:
    build:
      context: ./
      dockerfile: ./docker/AccountViewListener/dockerfile

  #######################################
  # client services
  #######################################
  account-client:
    build:
      context: ./
      dockerfile: ./docker/AccountClient/dockerfile

  #######################################
  # infrastructure services
  #######################################
  microservice-example-proxy:
    build:
      context: ./
      dockerfile: ./docker/Nginx/dockerfile

 


      