using Newtonsoft.Json;
using System;

namespace Domain.DomainEvents
{
    public abstract class DomainEvent<T>
    {
        private string EVENT_NAMESPACE;

        //Version of the aggregate
        public long Version { get; protected set; }

        //An id for the event, generated by the application
        public Guid Id { get; protected set; }
        
        //the id of the aggregate.  Typically a GUID but can be other types
        public string AggregateId { get; protected set; }

        //the .net namespace for the aggregate. used for reflection
        public string AggregateType => typeof(T).ToString();

        //time the event was created
        public DateTime CreatedOn { get; protected set; }

        //a string given to the event to define the messaging namespace.
        public string MessageNameSpace { get; protected set; }

        //A boolean representing as the event been successfully published
        public bool HasBeenPublished { get; protected set; }

        public DateTime? PublishedOn { get; protected set; }
       
        public DomainEvent(string aggregateid, string messageNameSpace)
            :this(Guid.NewGuid(), aggregateid, messageNameSpace, DateTime.UtcNow, false)
        {

        }

        public DomainEvent(Guid eventId, string aggregateId, string messageNameSpace, DateTime createdOn, bool hasBeenPublished)
        {
            this.CreatedOn = createdOn;
            this.Id = eventId;
            this.AggregateId = aggregateId;
            this.MessageNameSpace = messageNameSpace;
            this.HasBeenPublished = HasBeenPublished;
            this.CreatedOn = createdOn;
        }

        public DomainEvent(string EVENT_NAMESPACE)
        {
            this.EVENT_NAMESPACE = EVENT_NAMESPACE;
        }

        public void MarkPublished()
        {
            this.HasBeenPublished = true;
            this.PublishedOn = DateTime.UtcNow;
        }
    }
}
