FROM microsoft/aspnetcore-build:2 as builder

WORKDIR /src/shared/Domain
COPY /src/shared/Domain/Domain.csproj .
RUN dotnet restore

WORKDIR /src/shared/Logging
COPY /src/shared/Logging/Logging.csproj .
RUN dotnet restore

WORKDIR /src/shared/MongoEventStore
COPY /src/shared/MongoEventStore/MongoEventStore.csproj .
RUN dotnet restore

WORKDIR /src/services/account/Account.Core
COPY /src/services/account/Account.Core/Account.Core.csproj .
RUN dotnet restore

WORKDIR /src/services/account/Account.Data
COPY /src/services/account/Account.Data/Account.Data.csproj .
RUN dotnet restore

WORKDIR /src/services/account/Account.Proxies
COPY /src/services/account/Account.Proxies/Account.Proxies.csproj .
RUN dotnet restore

WORKDIR /src/services/account/Account.Application
COPY /src/services/account/Account.Application/Account.Application.csproj .
RUN dotnet restore

WORKDIR /src/services/account/Account.Api
COPY /src/services/account/Account.Api/Account.Api.csproj .
RUN dotnet restore

COPY /src/shared/Domain/ /src/shared/Domain/
COPY /src/shared/Logging/ /src/shared/Logging/
COPY /src/shared/MongoEventStore/ /src/shared/MongoEventStore/
COPY /src/services/account/Account.Core/ /src/services/account/Account.Core/
COPY /src/services/account/Account.Data/ /src/services/account/Account.Data/
COPY /src/services/account/Account.Proxies/ /src/services/account/Account.Proxies/
COPY /src/services/account/Account.Application/ /src/services/account/Account.Application/
COPY /src/services/account/Account.Api/ /src/services/account/Account.Api/

WORKDIR /src/services/account/Account.Api
RUN dotnet publish -c Release -o /build 

FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY --from=builder /build .

ENTRYPOINT [ "dotnet", "Account.Api.dll" ]