FROM microsoft/aspnetcore-build:2 as builder

WORKDIR /src/common/Domain
COPY /src/common/Domain/Domain.csproj .
RUN dotnet restore

WORKDIR /src/services/account-view/AccountView.Data
COPY /src/services/account-view/AccountView.Data/AccountView.Data.csproj .
RUN dotnet restore

WORKDIR /src/services/account-view/AccountView.Api
COPY /src/services/account-view/AccountView.Api/AccountView.Api.csproj .
RUN dotnet restore

COPY /src/common/Domain/ /src/common/Domain/
COPY /src/services/account-view/AccountView.Data/ /src/services/account-view/AccountView.Data/
COPY /src/services/account-view/AccountView.Api/ /src/services/account-view/AccountView.Api/

WORKDIR /src/services/account-view/AccountView.Api
RUN dotnet publish -c Release -o /build 

FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY --from=builder /build .

ENTRYPOINT [ "dotnet", "AccountView.Api.dll" ]