FROM microsoft/aspnetcore-build:2 as builder

WORKDIR /src/shared/Domain
COPY /src/shared/Domain/Domain.csproj .
RUN dotnet restore

WORKDIR /src/shared/Logging
COPY /src/shared/Logging/Logging.csproj .
RUN dotnet restore

WORKDIR /src/services/account-view/AccountView.Data
COPY /src/services/account-view/AccountView.Data/AccountView.Data.csproj .
RUN dotnet restore

WORKDIR /src/services/account-view/AccountView.Listener
COPY /src/services/account-view/AccountView.Listener/AccountView.Listener.csproj .
RUN dotnet restore

COPY /src/shared/Domain/ /src/shared/Domain/
COPY /src/shared/Logging/ /src/shared/Logging/
COPY /src/services/account-view/AccountView.Data/ /src/services/account-view/AccountView.Data/
COPY /src/services/account-view/AccountView.Listener/ /src/services/account-view/AccountView.Listener/

WORKDIR /src/services/account-view/AccountView.Listener
RUN dotnet publish -c Release -o /build 

FROM microsoft/aspnetcore:2.0

WORKDIR /app

COPY --from=builder /build .

ENTRYPOINT [ "dotnet", "AccountView.Listener.dll" ]